name: CD

on: push

jobs:
  PushImages:
    name: Build and push docker images
    runs-on: ubuntu-18.04

    steps:
      - name: Update Ubuntu
        run: sudo apt-get update

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER }}/yacs_n_db:${{ github.sha }} \
            -t ${{ secrets.DOCKER_USER }}/yacs_n_db:latest \
            src/data

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/yacs_n_db

